@startuml
package ...mainrepo.examples{
class ExampleTwo {
-thing1: string
-thing2: string
-thing3: string
-sayHi(): 
}
}
package ...mainrepo.examples{
class ExampleOne {
-thing1: string
-thing2: string
-thing3: string
-sayHi(): 
}
}

@enduml