@startuml
package ...mainrepo.examples{
class Example {
-thing1: string
-thing2: string
-thing3: string
-sayHi(): 
-sayBye(): 
-sayWhy(): 
}
}
package ...mainrepo.examples{
class ExampleTwo {
-thing1: string
-thing2: string
-thing3: string
-sayHi(): 
-sayBye(): 
-sayWhy(): 
}
}
package ...mainrepo.examples{
class ExampleThree {
-thing1: string
-thing2: string
-thing3: string
-sayHi(): 
-sayBye(): 
-sayWhy(): 
-sayAgain(): 
}
}

@enduml