name: Generate plantuml files

on:
  push:
    tags:
      - puml**
    branches:
      - master
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: checkout sourced
        uses: actions/checkout@v2
        with:
          path: './mainrepo'
      - name: checkoutplantuml
        uses: actions/checkout@v2
        with:
          repository: bykof/go-plantuml
          path: './plantuml'
      - name: run go stuff
        run: |
            cd ./plantuml
            go mod tidy
            go run . generate -d ../mainrepo -r
            cp graph.puml ../mainrepo/graph.puml
            git status
            git add ../mainrepo/graph.puml
            git status
            git commit -m 'testing'
            git push origin master
        shell: bash


