name: Generate plantuml files

on:
  push:
    tags:
      - puml**
    branches:
      - master
      - main
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate plantuml files
        uses: tbal999/go-plantuml@2
