name: Generate plantuml files

on:
  push:
    tags:
      - puml**
    branches:
      - master
      - main
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: checkout sourced
        uses: actions/checkout@v2
        with:
          path: './mainrepo'
      - name: checkoutplantuml
        uses: actions/checkout@v2
        with:
          repository: bykof/go-plantuml
          path: './plantuml'
      - name: run go stuff
        run: |
            cd ./plantuml
            go mod tidy
            go run . -d ../mainrepo -r
        shell: bash


