name: Generate plantuml files

on:
  push:
    tags:
      - puml**
    branches:
      - master
      - main
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: checkout source
        uses: actions/checkout@v2
        with:
          path: './mainrepo'
      - name: checkout & RUN plantuml
        uses: actions/checkout@v2
        with:
          repository: bykof/go-plantuml
          path: './plantuml'
          run: go run ./plantuml/main.go -d ../mainrepo -r
          shell: bash


