name: Generate plantuml files (.puml)

on:
  push:
    tags:
      - puml**
    branches:
      - master
      - main
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: checkout sourced
        uses: actions/checkout@v2
        with:
          path: './mainrepo'
          fetch-depth: 0
      - name: checkoutplantuml
        uses: actions/checkout@v2
        with:
          repository: bykof/go-plantuml
          path: './plantuml'
      - name: run go stuff
        run: |
            echo "START GO STUFF"
            cd ./plantuml
            go mod tidy
            go run . generate -d ../mainrepo -r
            echo "CHECK FOR GRAPH.PUML"
            ls -l | grep ".puml"
            echo "COPY..."
            cp graph.puml ../mainrepo
            cd ../mainrepo
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add graph.puml
            git commit -m "generated"
            git push

