name: Generate plantuml files (.puml)

#TODO
#Line 41 - need to set that as a constant so the date var doesn't change.

on:
  push:
    tags:
      - puml**
    branches:
      - master
      - main
  pull_request:
jobs:
  puml:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: './mainrepo'
          fetch-depth: 0
      - name: checkout plantuml
        uses: actions/checkout@v2
        with:
          repository: bykof/go-plantuml
          path: './plantuml'
      - name: create puml file
        run: |
            echo "START GO STUFF"
            cd ./plantuml
            go mod tidy
            go run . generate -d ../mainrepo -r
            echo "CHECK FOR GRAPH.PUML"
            ls -l | grep ".puml"
            echo "COPY..."
            cp graph.puml ../mainrepo/graph.puml
            cd ../mainrepo
            git config user.name github-actions
            git config user.email github-actions@github.com
            git pull
            git add graph.puml
            git diff-index --quiet HEAD || git commit -m "generated puml file"
            git push
            echo "END"
  diagrams:
    needs: puml
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tpng graph.puml
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "github-actions"
          commit_user_email: "github-actions@github.com"
          commit_author: "github-actions <github-actions@github.com>"
          commit_message: "Generate PNG image for PlantUML diagrams" 
          branch: ${{ github.head_ref }}
