name: Generate plantuml files (.puml)

#TODO
#Line 41 - need to set that as a constant so the date var doesn't change.

on:
  push:
    tags:
      - puml**
    branches:
      - master
      - main
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: checkout sourced
        uses: actions/checkout@v2
        with:
          path: './mainrepo'
          fetch-depth: 0
      - name: checkoutplantuml
        uses: actions/checkout@v2
        with:
          repository: bykof/go-plantuml
          path: './plantuml'
      - name: run go stuff
        run: |
            echo "START GO STUFF"
            cd ./plantuml
            go mod tidy
            go run . generate -d ../mainrepo -r
            echo "CHECK FOR GRAPH.PUML"
            ls -l | grep ".puml"
            echo "COPY..."
            cp graph.puml ../mainrepo/graph.puml
            cd ../mainrepo
            git config user.name github-actions
            git config user.email github-actions@github.com
            git pull
            git add graph.puml
            git diff-index --quiet HEAD || git commit -m "generated puml file"
            git push
            echo "END"
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-workflow-2
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
